WebApp/Models/Birthday.cs
namespace WebApp.Models;

public class Birthday
{
    public string? Name { get; set; }
    
    public DateTime? Date { get; set; }

    public bool IsValid()
    {
        return Name != null && Date != null;
    }

    public int Birth()
    {
        if (Date == null)
        {
            throw new InvalidOperationException("Date cannot be null.");
        }
        
        DateTime today = DateTime.Now;
        int age = today.Year - Date.Value.Year;
        
        if (Date.Value.Date > today.AddYears(-age)) throw new InvalidOperationException("Date cannot be greater than today year.");
        
        return age;
    }
}

WebApp/Models/Calculator.cs
using WebApp.Controllers;

namespace WebApp.Models;

public class Calculator
{
    public Operators? Operator { get; set; }
    public double? X { get; set; }
    public double? Y { get; set; }

    public String Op
    {
        get
        {
            switch (Operator)
            {
                case Operators.Add:
                    return "+";
                
                case Operators.Sub:
                    return "-";
                
                case Operators.Mul:
                    return "*";
                
                case Operators.Div:
                    return ":";
                
                default:
                    return "";
            }
        }
    }

    public bool IsValid()
    {
        return Operator != null && X != null && Y != null;
    }

    public double Calculate() {
        switch (Operator)
        {
            case Operators.Add:
                return (double) (X + Y);
            
            case Operators.Sub:
                return (double) (X - Y);
            
            case Operators.Mul:
                return (double) (X * Y);
            
            case Operators.Div:
                return (double) (X / Y);
            
            default: return double.NaN;
        }
    }
    
}

WebApp/Models/ContactModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Models;

public class ContactModel
{
    [HiddenInput]
    public int Id { get; set; }
    
    [Required(ErrorMessage = "Musisz wpisać imię!")]
    [MaxLength(length:20, ErrorMessage = "Imię nie może być dłuższe niż 20 znaków")]
    [MinLength(length:2, ErrorMessage = "Imię musi mieć conajmniej 2 znaki!")]
    public string FirstName { get; set; }
    
    [Required(ErrorMessage = "Musisz wpisać nazwisko!")]
    [MaxLength(length:50, ErrorMessage = "Nazwisko nie może być dłuższe niż 50 znaków")]
    [MinLength(length:2, ErrorMessage = "Nazwisko musi mieć conajmniej 2 znaki!")]
    public string LastName { get; set; }
    
    [EmailAddress]
    public string Email { get; set; }
    
    [Phone]
    [RegularExpression("\\d{3} \\d{3} \\d{3}", ErrorMessage = "Wpisz numer wg wzoru: XXX XXX XXX")]
    public string PhoneNumber { get; set; }
    
    [DataType(DataType.Date)]
    public DateOnly BirthDate { get; set; }
    
}

WebApp/Models/ErrorViewModel.cs
namespace WebApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WebApp/Controllers/BirthController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers;

public class BirthController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
    
    public IActionResult BirthdayResult(Birthday birth)
    {
        if (!birth.IsValid())
        {
            return View("Error");
        }

        return View(birth);
    }
    
    public IActionResult BirthdayForm()
    {
        return View();
    }
}

WebApp/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers;

public class CalculatorController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult Result([FromForm] Calculator model)
    {
        if (!model.IsValid())
        {
            return View("Error");
        }
        return View(model);
    }
    
    public IActionResult Form()
    {
        return View();
    }
}

WebApp/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers;

public class ContactController : Controller
{
    private static Dictionary<int, ContactModel> _contacts = new()
    {
        {
            1, new ContactModel()
            {
                Id = 1,
                FirstName = "John",
                LastName = "Smith",
                Email = "john.smith@gmail.com",
                PhoneNumber = "111 222 333",
                BirthDate = new DateOnly(1985, 9, 9),
            }
        },
        {
            2, new ContactModel()
            {
                Id = 2,
                FirstName = "Jack",
                LastName = "Kowalski",
                Email = "jack.kowalski@gmail.com",
                PhoneNumber = "123 456 789",
                BirthDate = new DateOnly(1975, 10, 10),
            }
        },
        {
            3, new ContactModel()
            {
                Id = 3,
                FirstName = "Kuba",
                LastName = "Nowak",
                Email = "kuba.nowak@gmail.com",
                PhoneNumber = "666 666 666",
                BirthDate = new DateOnly(1977, 5, 15),
            }
        }
        
    };

    private static int _currentId = 3;
    
    // Lista kontaktów
    public IActionResult Index()
    {
        return View(_contacts);
    }

    // Zwraca formularz dodania kontaktu
    [HttpGet]
    public IActionResult Add()
    {
        return View();
    }
    
    // Odebranie danych z formularzu, zapisanie kontaktu i powrót do listy kontaktów
    [HttpPost]
    public IActionResult Add(ContactModel model)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }
        // dodanie kontaktu
        model.Id = ++_currentId;
        _contacts.Add(model.Id, model);
        return View("Index", _contacts);
    }

    public IActionResult Delete(int id)
    {
        _contacts.Remove(id);
        return View("Index", _contacts);
    }

    public IActionResult Details(int id)
    {
        return View(_contacts[id]);
    }
}

WebApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }
    
    
    
    /*
     * Zadanie domowe
     * Napisz metodę Age, która przyjmuje parametr z datą urodzin i wyświetla wiek
     * w latach, miesiącach i dniach.
     */

    public IActionResult Calculator(Operators? op, double? x, double? y)
    {
        //https://localhost:7182/Home/Calculator?op=div&x=8&y=4
        //var op = (Request.Query["op"]);
        //var x = double.Parse(Request.Query["x"]);
        //var y = double.Parse(Request.Query["y"]);
        if (x is null || y is null)
        {
            ViewBag.ErrorMessage = "Niepoprawny format liczby x lub y lub brak parametru!";
            return View("CalculatorError");
        }

        if (op is null)
        {
            ViewBag.ErrorMessage = "Nieznany operator!";
            return View("CalculatorError");
        }
        
        double? result = 0.0d;
        switch (op)
        {
            case Operators.Add:
                result = x + y;
                ViewBag.Operator = "+";
                break;
            case Operators.Sub:
                result = x - y;
                ViewBag.Operator = "-";
                break;
            case Operators.Mul:
                result = x * y;
                ViewBag.Operator = "*";
                break;
            case Operators.Div:
                result = x / y;
                ViewBag.Operator = ":";
                break;
        }
        ViewBag.Result = result;
        ViewBag.X = x;
        ViewBag.Y = y;
        return View();
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult About()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

public enum Operators
{
    Add, Sub, Mul, Div
}

WebApp/Views/Birth/BirthdayForm.cshtml
@model dynamic

@{
    ViewBag.Title = "Obliczanie wieku";
    Layout = "_Layout";
}

<div>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6">
                <h2>Obliczanie wieku</h2>
                <form action="BirthdayResult" method="GET">
                    <div class="mb-3">
                        <label class="form-label" for="Name">Podaj Imię:</label>
                        <input class="form-control" type="text" Name="Name" id="Name"/>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="Date">Podaj datę urodzenia: </label>
                        <input class="form-control" type="Date" name="Date" id="Date"/>
                    </div>
                    <div class="mb-3">
                        <button class="btn btn-primary" type="submit">Oblicz wiek</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

WebApp/Views/Birth/BirthdayResult.cshtml
@model WebApp.Models.Birthday

@{
    ViewBag.Title = "Wynik";
    Layout = "_Layout";
}
<h2>@ViewBag.Title</h2>
<h2>Cześć @Model.Name, masz @Model.Birth() lat(a) </h2>

WebApp/Views/Birth/Form.cshtml
@model dynamic

@{
    ViewBag.Title = "Obliczanie wieku";
    Layout = "_Layout";
}

<div>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6">
                <h2>Obliczanie wieku</h2>
                <form action="Result" method="GET">
                    <div class="mb-3">
                        <label class="form-label" for="Name">Podaj Imię:</label>
                        <input class="form-control" type="text" Name="Name" id="Name"/>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="Date">Podaj datę urodzenia: </label>
                        <input class="form-control" type="Date" name="Date" id="Date"/>
                    </div>
                    <div class="mb-3">
                        <button class="btn btn-primary" type="submit">Oblicz wiek</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

WebApp/Views/Calculator/Form.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Kalkulator</h2>
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <h2>Oblicz</h2>
            <form action="Result" method="POST">
                <div class="mb-3">
                    <label class="form-label" for="x">Liczba 1</label>
                    <input class="form-control" type="number" name="x" step="0.00001" id="x"/>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="operator">Operator</label>
                    <select name="operator">
                        <option value="add">+</option>
                        <option value="sub">&minus;</option>
                        <option value="mul">&times;</option>
                        <option value="div">&divide;</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="y">Liczba 2</label>
                    <input class="form-control" type="number" name="y" step="0.00001" id="y"/>
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Oblicz</button>
                </div>
            </form>
        </div>
    </div>
</div>

WebApp/Views/Calculator/Result.cshtml
@model Calculator
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<H3>@Model.X @Model.Op @Model.Y = <b class="text-danger">@Model.Calculate()</b></H3>

WebApp/Views/Contact/Add.cshtml
@model ContactModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Dodaj kontakt</h2>
<form asp-action="Add" method="post">
    <div class="mb-3">
        <label class="form-label" asp-for="FirstName">Imię</label>
        <input class="form-control" asp-for="FirstName"/>
        <span class="text-danger" asp-validation-for="FirstName"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="LastName">Nazwisko</label>
        <input class="form-control" asp-for="LastName"/>
        <span class="text-danger" asp-validation-for="LastName"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Email">Email</label>
        <input class="form-control" asp-for="Email"/>
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="PhoneNumber">Numer telefonu</label>
        <input class="form-control" asp-for="PhoneNumber"/>
        <span class="text-danger" asp-validation-for="PhoneNumber"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="BirthDate">Data urodzenia</label>
        <input class="form-control" asp-for="BirthDate"/>
        <span class="text-danger" asp-validation-for="BirthDate"></span>
    </div>
    <button type="submit" class="btn btn-outline-primary">Dodaj</button>
    <button type="reset" class="btn btn-danger">Wyczyść</button>
</form>

WebApp/Views/Contact/Details.cshtml
@model ContactModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

//TODO dodać powrót do kontaktów
<h2>Szczegóły kontaktu:</h2>
<h3>@Model.FirstName @Model.LastName</h3>
<p>Email</p>
<h4>@Model.Email</h4>
<p>Numer telefonu</p>
<h4>@Model.PhoneNumber</h4>
<p>Data urodzenia</p>
<h4>@Model.BirthDate</h4>

WebApp/Views/Contact/Index.cshtml
@model System.Collections.Generic.Dictionary<int,WebApp.Models.ContactModel>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Kontakty</h2>
<a class="btn btn-primary" asp-action="Add" asp-controller="Contact">Dodaj kontakt</a>
<h4 class="mb-3">Lista kontaktów</h4>
<table class="table">
    <thead>
    <tr>
        <th>
            Imię
        </th>
        <th>
            Nazwisko
        </th>
        <th>
            Operacje
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var entry in @Model)
    {
        <tr>
            <td>
                @entry.Value.FirstName
            </td>
            <td>
                @entry.Value.LastName
            </td>
            <td>
                <a class="btn btn-success">Edytuj</a>
                <a class="btn btn-info" asp-action="Details" asp-controller="Contact" asp-route-id="@entry.Key">Szczegóły</a>
                <a class="btn btn-danger" asp-action="Delete" asp-controller="Contact" asp-route-id=@entry.Key>Usuń</a>
            </td>
        </tr>
    }
    </tbody>
</table>

WebApp/Views/Home/About.cshtml
@model dynamic

@{
    ViewBag.Title = "About";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>
<h3>Created by Jakub Opoka</h3>

WebApp/Views/Home/Age.cshtml
@model dynamic
@{
    ViewBag.Title = "Wiek";
}
<h2>Wiek</h2>
@if(ViewBag.Error != null)
{
    <div style="color: red;">@ViewBag.Error</div>
}
else
{
    <p>Data urodzenia: @ViewBag.Birhtday.ToString("dd-MM-yyyy")</p>
    <p>Lata: @ViewBag.Years</p>
    <p>Miesiące: @ViewBag.Months</p>
    <p>Dni: @ViewBag.Days</p>
}

WebApp/Views/Home/Calculator.cshtml
@model dynamic

@{
    ViewBag.Title = "Calculator";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>
<h3>Wynik obliczeń: @ViewBag.X @ViewBag.Operator @ViewBag.Y = @ViewBag.Result</h3>

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApp/Views/Shared/CalculatorError.cshtml
@{
    ViewBag.Title = "Blad kalkulatora";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>
<h3>@ViewBag.ErrorMessage</h3>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Calculator</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="BirthdayForm">Birth Calculator</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Contact" asp-action="Index">Contacts</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>